name: Automated Sync to Hugging Face Hub

on:
  push:
    branches: [main] # Triggers the sync every time you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push Code to Hugging Face Spaces Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Force push code directly to the Hugging Face space repository
          git push --force https://Gourav28:$HF_TOKEN@huggingface.co/spaces/Gourav/AI-Recruiter main
